### ISSUE TITLE
Website table displays columns which have no data

### ISSUE THREAD

**Issue by jarednielsen** [wandb/wandb#1144]
Here's my use case: I accidentally add a faulty field to the config when logging a wandb run. I realize the error, remove the field from my Python config, and delete the run which contained the faulty field. However, the field (which exists in no runs) persists in the table. Is there a way to "refresh" the table so it only loads columns which contain data?

<img width="1200" alt="Screen Shot 2020-07-08 at 12 46 20 AM" src="https://user-images.githubusercontent.com/4564897/86891978-7bb00180-c0b4-11ea-9f30-edf03de6f693.png">

**Comment by vanpelt** [comment]
Hey @jarednielsen in upper right hand corner of the table theres a "Magic Wand" icon.  Clicking that should remove all columns that don't contain any information.  I'll keep this open as we should just remove them from the column options when no existing runs contain them.  Let me know if the "Magic Wand" trick doesnt work for your project.

**Comment by ariG23498** [comment]
Hey @jarednielsen 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing stale issues. Please comment to reopen. :smile:

**Comment by mcourteaux** [comment]
I think this issue persists. The columns should be removed when there are no longer runs having them.

**Comment by aidanjdonohue** [comment]
Hi @mcourteaux , could you link me to a project page where this is happening for you?

**Comment by mcourteaux** [comment]
Hi @aidanjdonohue! I don't have a public project on WandB. If you can access my private project anyway, it's called "MoonBot", username is the same here as on GitHub. Problematic columns include `weight_regularizator_l1` and `weight_regularizator_l2`, which obviously was a spelling mistake, so I corrected it, deleted all the runs that had this column. The column displays `-` everywhere, for all runs (no filters). The magic wand does indeed hide is, but it's still there.

**Comment by aidanjdonohue** [comment]
Hi @mcourteaux, ahh I see. I've linked this to our internal ticket but am going to keep this thread closed until we push the full fix. For now, the magic wand is the way to go.

**Comment by mcourteaux** [comment]
Hi @aidanjdonohue ! Thank you for paying attention to what I'm saying. Really nice! Cheers :)

**Comment by LarsHill** [comment]
For me the problem persists as well and the magic wand does not remove columns that don't contain any data. A fix would be great.

**Comment by MonliH** [comment]
A quick workaround I found was to just move all the runs to a new project, delete the old project, then rename the new project.

**Comment by lesliewandb** [comment]
I'm glad you were able to find a workaround on it. If this happens again, I would recommend to clear your workspace on the bottom left of your page where it says 'My Workspaces'. But since it looks like there's a workaround that has worked for you, I'll close this ticket out

**Comment by weiyaw** [comment]
Is there a plan to implement this feature in the near future, rather than relying on a workaround?

**Comment by ringohoffman** [comment]
@lesliewandb Is copying and deleting an entire project the official solution for deleting columns?
