### ISSUE TITLE
[CLI]: Ctrl+C to kill process leaves "wandb: / 0.124 MB of 0.124 MB uploaded (0.000 MB deduped)" message in shell

### ISSUE THREAD

**Issue by lwaekfjlk** [wandb/wandb#5244]
### Describe the bug

When I use Ctrl+C to terminate a process that has wandb running, I sometimes notice that a message remains in the shell stating: "wandb: / 0.124 MB of 0.124 MB uploaded (0.000 MB deduped)". This line of text persists and continues refreshing in the shell, which can be quite distracting. I am unable to clear this message from the shell.

### Additional Files

![截屏2023-03-25 20 15 18](https://user-images.githubusercontent.com/49915633/227748404-a288f769-8de8-42aa-9fca-546b72e1737c.png)
Here is a image of what I often occur.

### Environment

WandB version: 0.13.7

OS: Ubuntu 18.04.6

Python version: 3.8.0

Versions of relevant libraries: No

**Comment by MBakirWB** [comment]
HI @lwaekfjlk , thank you for writing in and happy to help. With this particular behavior 

Regarding the behavior you mentioned, I would expect to see the following message repeating: `wandb: - 0.000 MB of 0.009 MB uploaded (0.000 MB deduped)`. This could be caused by any of the following reasons:

- Standard logging, indicating progress - safe to ignore
- User decides to kill a  wandb process manually causing single/multiple process to hang
- wandb service is trying to finish a run that for some reason doesn't exist, but caused by multiple finishes from different contexts

To better understand your situation, it would be helpful if you could provide me with some additional details about your experiment setup. This could include information about your environment, such as whether you are running the experiment on a local machine, a container, or an external instance. If you are executing multiple runs in parallel or using distributed training. If you are logging data other than scalars, what's the type of data and its approximate size.

Finally, if possible, please provide me with the `debug.log` and d`ebug-internal.log` files from your working directory for one of the runs that are hanging.

Thanks

**Comment by rishabh-ranjan** [comment]
Hi, I am also facing the same problem. I would like to configure wandb to not produce such messages. I have WANDB_SILENT set to "true", but that didn't help. Is this at all possible? The "uploaded" message after Ctrl+C is very annoying, especially since it continues to refresh in background and doesn't go away even after clearing the screen at the terminal.

**Comment by MBakirWB** [comment]
Hi @rishabh-ranjan , could you provide me the `debug.log` and `debug-internal.log` files from your working directory for one of the runs that is hanging. Also set WANDB_CONSOLE to "off" and attempt to repro this.

**Comment by MBakirWB** [comment]
Hi @rishabh-ranjan, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by pmcvay** [comment]
I can confirm this behavior and can confirm that it is extremely annoying and no matter what command I type in the terminal, the upload pops up again blocking my view of anything

**Comment by sherlcok314159** [comment]
You can just use this command to kill wandb in terminal. (Note: this will kill all the processes related to wandb)

```bash
ps aux|grep wandb|grep -v grep | awk '{print $2}'|xargs kill -9
```

**Comment by taesungp** [comment]
I have to say this behavior is annoying, because it makes the bash shell unusable. I could follow @sherlcok314159 's suggestion to manually kill the process, but I can only do it when I don't have any other wandb sessions running on the same machine. Is there any way to disable this output? The message is not really informative to the user.

**Comment by lulmer** [comment]
Up it is so annoying :`wandb: - 1.111 MB of 1.111 MB uploaded (0.000 MB deduped)`

**Comment by pableeto** [comment]
I also encountered this issue - it is annoying indeed.

**Comment by sgmath12** [comment]
This is so annoyging

**Comment by isdanni** [comment]
Following, encountered the same issue

**Comment by Githuber-zwb** [comment]
I have the same problem, and it's really annoying.

**Comment by joonleesky** [comment]
I have the same problem as well.

**Comment by spfrommer** [comment]
Same issue!

**Comment by HouNic97** [comment]
ANNOYING indeed！When you are testing your  program, you can first try entering "wandb disabled" to disable wandb. Once the test passes, you can enable it again to record your data. You can first enter "wandb" to view all its commands.

**Comment by seanxuu** [comment]
same here

**Comment by oliver-batchelor** [comment]
Most annoying thing about WanDB - enough that I almost want to change framework JUST because of this.

**Comment by L-Reichardt** [comment]
Same, happens in basically ever 4th training run.

**Comment by elisim** [comment]
Same, very annoying

**Comment by CarlosMari** [comment]
Same here, I just end up restarting terminal every time to get rid of it.

**Comment by dongzhuoyao** [comment]
> I have to say this behavior is annoying, because it makes the bash shell unusable. I could follow @sherlcok314159 's suggestion to manually kill the process, but I can only do it when I don't have any other wandb sessions running on the same machine. Is there any way to disable this output? The message is not really informative to the user.

Can someone solve this issue for me?

**Comment by richardrl** [comment]
still happening

**Comment by CarlosMari** [comment]
So, in cases where I am the one killing the script which then gets wandb stuck, I realized that if I just Ctrl+C once, then wait for a minute for wandb to log and then Ctrl+C again, the issue does not happen.

**Comment by ToryDeng** [comment]
I use `wandb` version 0.17.0 and this issue still exists. Very annoying. I hope it can be resolved soon.

**Comment by Breeze-Zero** [comment]
Me too.

**Comment by fireblue95** [comment]
same issue

**Comment by xuChenSJTU** [comment]
same issue

**Comment by fireblue95** [comment]
@xuChenSJTU 
Got a solution here: https://github.com/wandb/wandb/issues/4929#issuecomment-2195850571

**Comment by AmericanPresidentJimmyCarter** [comment]
`ps -auxwe | grep "wandb" | awk '{print $2}' | xargs kill -9`

**Comment by sven-nm** [comment]
Same issue here, really annoying.

**Comment by SteveImmanuel** [comment]
still happening

**Comment by chenxshuo** [comment]
same issue is still happening

**Comment by thomassajot** [comment]
Also experiencing the same issue. I will experiment with adding a call to `wandb.finish()` on segterm.
In the meantime I use `pkill -u <username> -f wandb` to close off all wandb for my user.

**Comment by and-rewsmith** [comment]
To the authors of the repo:

This has been an issue a long time. I am sure that there is some justification. But from a product standpoint I feel that the fact a mitigation has not occurred is a big blunder. It has severely impacted my perception of both the product and the dev team priorities.

Every machine I develop on I need to setup a kill script to mitigate it. Every time I curse wandb for me having to do it. Every occurrence of this I check the calendar and cannot believe it is still an issue. 

It would be a good signal to the internal culture if when your developers use your product, they feel this pain, so then they either fix or mitigate it. Why this has not happened in years is not clear, and the answer does not seem good for you, but you are in a better place to infer it than me.

**Comment by luisbergua** [comment]
Hello all,

Luis from the Engineering Support Team here. First of all, please accept our sincere apologies for the radio silence. Unfortunately, we missed the notifications for this thread, which caused the delay in our responses.

We've recently released our new backend, wandb-core (details [here](https://github.com/wandb/wandb/blob/main/core/README.md)), which is now the default one from version 0.18.0. This update should resolve the issue you've been facing, alongside other major improvements like significantly faster processing, so I encourage you all to install the latest version.

I've enabled email alerts for this thread moving forward so please do reach out to us either here or via support@wandb.com if you still see the issue after upgrading, and we'll investigate. We truly appreciate all the feedback and look forward to continuing to improve the tool with your help, so please keep it going!

**Comment by frederiknolte** [comment]
I still have the same issue. The only solution is manually killing the process

**Comment by and-rewsmith** [comment]
My machine hung today due to OOM. My gut feeling is that this is related to the above issue and is caused by processes not exiting. I am not on the latest version, but you should confirm this is also fixed.

<details>
  <summary>Click to see details</summary>

  My machine hung today due to OOM. My gut feeling is that this is related to the above issue and is caused by processes not exiting. 

  ![Image](https://github.com/user-attachments/assets/a13873aa-53b1-42fc-b9fe-1d6c8d84da2d)
</details>

@luisbergua And while I appreciate the sentiment of your message, it reads to me like a PR response. There are multiple issues for this, with employee interaction, milestone adjustments, etc. Awareness does not seem like the issue here. 

Developers have allowed this sort of behavior to go unresolved for years. That is the issue in my eyes.

The type of response received here, to me, reinforces the idea that there is some structurally wrong driving this pain. I think a more appropriate response to this issue would be to acknowledge it. It isn't a big deal if you all can fix it. You have a great product otherwise.

**Comment by luisbergua** [comment]
Hi @frederiknolte and @and-rewsmith, sorry to hear that the issue is still appearing, and thanks for sharing this feedback @and-rewsmith, it's really valuable for us. Let me please reach out to our engineers on this, I'll check with them and provide an update here.

**Comment by luisbergua** [comment]
@and-rewsmith just checked with our engineers, based on the screenshot you shared it seems you're running `wandb-service(...)`, which is name the old python service, so may I please ask what's your `wandb --version`?

@frederiknolte noted that you're on `0.18.5`, so checking with our engineers

**Comment by luisbergua** [comment]
Hey @frederiknolte, I have did multiple tests on my end, but was unable to reproduce this behavior on `0.18.5`. If you're able to reproduce this consistently, may I please ask for a code example or some steps to reproduce?

@and-rewsmith please let us know if you noticed any improvements after upgrading to `wandb>=0.18.0`

**Comment by luisbergua** [comment]
Hey @frederiknolte @and-rewsmith, since we haven't heard back and were unable to reproduce this on  `wandb>=0.18.0` we'll close this for now. If you have a consistent reproduction of the issue, please feel free to ping me here and share it and I will test on my end

**Comment by nicosquare** [comment]
> You can just use this command to kill wandb in terminal. (Note: this will kill all the processes related to wandb)
> 
> ps aux|grep wandb|grep -v grep | awk '{print $2}'|xargs kill -9

I confirm this approach works, although it might kill your other running wandb processes. You can still narrow down the problematic PID and kill it.
